In [ ]:
#1.
""" Bir vektör tek boyutlu bir dizidir(array). 
(satır ve sutun vektörleri arasında herhangi bir fark yoktur.)
Ancak bir matris iki boyutlu bir dizidir.
3-Boyutlu veya daha yüksek boyutlu diziler için tensor kavramı kullanılır."""

In [1]:
#2.
import numpy as np
a_list=[0,1,2,3,4,5,6,7,8,9]
an_array=np.array(a_list)
an_array



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#3.
from display_shape import display_shape
a_matrix=np.zeros((10,10), dtype=int)
display_shape(a_matrix)


[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Number of elements in a= 100
Number of dimensions in a= 2
Rows and Columns in a (10, 10)



In [8]:
#4.
a_matrix=np.ones((10,10))
display_shape(a_matrix)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Number of elements in a= 100
Number of dimensions in a= 2
Rows and Columns in a (10, 10)



In [2]:
import numpy as np
from display_shape import display_shape
#5.
#a_matrix=np.ones((10,10),dtype=int)
#display_shape(9*a_matrix)
a_matrix=np.full((10,10),9)
display_shape(a_matrix)


[[9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]]
Number of elements in a= 100
Number of dimensions in a= 2
Rows and Columns in a (10, 10)



In [14]:
#6.
a_array=np.arange(5,25,3)
display_shape(a_array)


[ 5  8 11 14 17 20 23]
Number of elements in a= 7
Number of dimensions in a= 1
Rows and Columns in a (7,)



In [3]:
#7.
a_array=np.linspace(-1,1,30)
display_shape(a_array)



[-1.         -0.93103448 -0.86206897 -0.79310345 -0.72413793 -0.65517241
 -0.5862069  -0.51724138 -0.44827586 -0.37931034 -0.31034483 -0.24137931
 -0.17241379 -0.10344828 -0.03448276  0.03448276  0.10344828  0.17241379
  0.24137931  0.31034483  0.37931034  0.44827586  0.51724138  0.5862069
  0.65517241  0.72413793  0.79310345  0.86206897  0.93103448  1.        ]
Number of elements in a= 30
Number of dimensions in a= 1
Rows and Columns in a (30,)



In [11]:
#8.
a_matrix=np.random.randint(0,30,(5,6))
display_shape(a_matrix)


[[ 0  0  2 18 28  3]
 [11  9 29  7 21 18]
 [14  1 26 23  8 15]
 [21 27  4 11 16 21]
 [16  8 22 16  6 20]]
Number of elements in a= 30
Number of dimensions in a= 2
Rows and Columns in a (5, 6)



In [15]:
#9.
a_matrix=np.full((10,10),9)
np.fill_diagonal(a_matrix,1)
display_shape(a_matrix)



[[1 9 9 9 9 9 9 9 9 9]
 [9 1 9 9 9 9 9 9 9 9]
 [9 9 1 9 9 9 9 9 9 9]
 [9 9 9 1 9 9 9 9 9 9]
 [9 9 9 9 1 9 9 9 9 9]
 [9 9 9 9 9 1 9 9 9 9]
 [9 9 9 9 9 9 1 9 9 9]
 [9 9 9 9 9 9 9 1 9 9]
 [9 9 9 9 9 9 9 9 1 9]
 [9 9 9 9 9 9 9 9 9 1]]
Number of elements in a= 100
Number of dimensions in a= 2
Rows and Columns in a (10, 10)



In [18]:
#10.
import numpy as np
a_matrix=np.random.randint(0,10,(5,10))
print(a_matrix)
print(a_matrix.size)
print(a_matrix.ndim)
print(a_matrix.shape)
print(a_matrix.dtype)



[[4 4 7 8 6 1 0 7 7 4]
 [1 5 5 4 0 9 4 6 6 6]
 [2 3 3 8 9 9 7 8 6 0]
 [1 0 9 5 3 7 3 9 3 2]
 [8 4 2 2 3 1 0 2 3 8]]
50
2
(5, 10)
int32


In [33]:
#11.
import numpy as np
np.random.seed(0)
x3=np.random.randint(10,size=(3,4,7))
x3

array([[[5, 0, 3, 3, 7, 9, 3],
        [5, 2, 4, 7, 6, 8, 8],
        [1, 6, 7, 7, 8, 1, 5],
        [9, 8, 9, 4, 3, 0, 3]],

       [[5, 0, 2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1, 9, 9],
        [0, 4, 7, 3, 2, 7, 2],
        [0, 0, 4, 5, 5, 6, 8]],

       [[4, 1, 4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6, 7, 2],
        [0, 3, 5, 9, 4, 4, 6],
        [4, 4, 3, 4, 4, 8, 4]]])

In [4]:
#12.
import numpy as np
a_array=np.arange(12)
print(a_array)
a_matrix=a_array.reshape(3,4)
print(a_matrix)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
#13.
import numpy as np
from display_shape import display_shape
x1=np.arange(4)
x2=np.arange(4)
x3=np.arange(4)
x4=np.arange(4)
a=np.concatenate([x1,x2,x3,x4])
display_shape(a)



[0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3]
Number of elements in a= 16
Number of dimensions in a= 1
Rows and Columns in a (16,)



In [15]:
#14.
x1=np.arange(3).reshape(3,1)
display_shape(x1)
x2=np.arange(9).reshape(3,3)
display_shape(x2)
#a=np.hstack([x1,x2])
a=np.concatenate([x1,x2],axis=1)
display_shape(a)


[[0]
 [1]
 [2]]
Number of elements in a= 3
Number of dimensions in a= 2
Rows and Columns in a (3, 1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
Number of elements in a= 9
Number of dimensions in a= 2
Rows and Columns in a (3, 3)


[[0 0 1 2]
 [1 3 4 5]
 [2 6 7 8]]
Number of elements in a= 12
Number of dimensions in a= 2
Rows and Columns in a (3, 4)



In [ ]:
#15.
"""Axis bir arrayin boyutu anlamındadır. İki boyutlu bir vektörde, axis 0 satırları, axis 1 sütunları gösterir. """

In [1]:
#16.
import numpy as np
from display_shape import display_shape

np.random.seed(0)
a1=np.random.randint(0,10,(3,4))
a11=np.random.randint(0,20,(3,2))
a2=np.random.randint(0,20,(4,3))
a22=np.random.randint(0,10,(2,3))

a3=np.concatenate((a1,a11),axis=1)
display_shape(a3)
a4=np.concatenate((a2,a22),axis=0)
display_shape(a4)



[[ 5  0  3  3 12  1]
 [ 7  9  3  5  6  7]
 [ 2  4  7  6 14 17]]
Number of elements in a= 18
Number of dimensions in a= 2
Rows and Columns in a (3, 6)


[[ 5 13  8]
 [ 9 19 16]
 [19  5 15]
 [15  0 18]
 [ 3  8  1]
 [ 3  3  3]]
Number of elements in a= 18
Number of dimensions in a= 2
Rows and Columns in a (6, 3)



In [5]:
#17.
a_array=np.arange(10)
display_shape(a_array)
a1,a2,a3,a4,a5=np.split(a_array,[2,4,6,8])
print(a1,a2,a3,a4,a5)


[0 1 2 3 4 5 6 7 8 9]
Number of elements in a= 10
Number of dimensions in a= 1
Rows and Columns in a (10,)

[0 1] [2 3] [4 5] [6 7] [8 9]


In [40]:
#18.
np.random.seed(0)
a1=np.random.randint(0,10,(4,3))
display_shape(a1)
a1.sort(axis=0)
print(a1,end="\n\n")
print(a1.argsort())


[[5 0 3]
 [3 7 9]
 [3 5 2]
 [4 7 6]]
Number of elements in a= 12
Number of dimensions in a= 2
Rows and Columns in a (4, 3)

[[3 0 2]
 [3 5 3]
 [4 7 6]
 [5 7 9]]

[[1 2 0]
 [0 2 1]
 [0 2 1]
 [0 1 2]]


In [47]:
#19.
np.random.seed(0)
a1=np.random.randint(0,10,size=20)
print(a1)
print(a1[2],a1[4],a1[6])

[5 0 3 3 7 9 3 5 2 4 7 6 8 8 1 6 7 7 8 1]
3 7 3


In [49]:
#20.
np.random.seed(0)
a1=np.random.randint(0,10,size=10)
print(a1)
a1[5]=999
print(a1)

[5 0 3 3 7 9 3 5 2 4]
[  5   0   3   3   7 999   3   5   2   4]


In [ ]:
#21.


In [7]:
#masterodev.
import numpy as np
import time
start_time = time.time()
count = 0
# flag = 1
number = 3
while True:
    count += 1
    mat_1 = np.random.random((2, 2))
    # print('mat1', mat_1 )
    mat_2 = np.random.random((2,2))
    # print('mat2', mat_2 )
    diago = np.diag(mat_1 - mat_2)
    # print('diago', diago)
    if 10 < diago.any() and diago.any() < 10:
        print('I got it!')
        print('diago', diago)
        break
    else:
        continue
finish_time = time.time()
print('Elapsed Time : ', finish_time - start_time )
print()
print('Loop Number  : ', count)
print()
print('Matris       : ', mat_1 - mat_2)
print()

KeyboardInterrupt: 