In [ ]:
#1.
""" Bir vektör tek boyutlu bir dizidir(array). 
(satır ve sutun vektörleri arasında herhangi bir fark yoktur.)
Ancak bir matris iki boyutlu bir dizidir.
3-Boyutlu veya daha yüksek boyutlu diziler için tensor kavramı kullanılır."""

In [1]:
#2.
import numpy as np
a_list=[0,1,2,3,4,5,6,7,8,9]
an_array=np.array(a_list)
an_array



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#3.
from display_shape import display_shape
a_matrix=np.zeros((10,10), dtype=int)
display_shape(a_matrix)


[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Number of elements in a= 100
Number of dimensions in a= 2
Rows and Columns in a (10, 10)



In [8]:
#4.
a_matrix=np.ones((10,10))
display_shape(a_matrix)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Number of elements in a= 100
Number of dimensions in a= 2
Rows and Columns in a (10, 10)



In [2]:
import numpy as np
from display_shape import display_shape
#5.
#a_matrix=np.ones((10,10),dtype=int)
#display_shape(9*a_matrix)
a_matrix=np.full((10,10),9)
display_shape(a_matrix)


[[9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]]
Number of elements in a= 100
Number of dimensions in a= 2
Rows and Columns in a (10, 10)



In [14]:
#6.
a_array=np.arange(5,25,3)
display_shape(a_array)


[ 5  8 11 14 17 20 23]
Number of elements in a= 7
Number of dimensions in a= 1
Rows and Columns in a (7,)



In [3]:
#7.
a_array=np.linspace(-1,1,30)
display_shape(a_array)



[-1.         -0.93103448 -0.86206897 -0.79310345 -0.72413793 -0.65517241
 -0.5862069  -0.51724138 -0.44827586 -0.37931034 -0.31034483 -0.24137931
 -0.17241379 -0.10344828 -0.03448276  0.03448276  0.10344828  0.17241379
  0.24137931  0.31034483  0.37931034  0.44827586  0.51724138  0.5862069
  0.65517241  0.72413793  0.79310345  0.86206897  0.93103448  1.        ]
Number of elements in a= 30
Number of dimensions in a= 1
Rows and Columns in a (30,)



In [11]:
#8.
a_matrix=np.random.randint(0,30,(5,6))
display_shape(a_matrix)


[[ 0  0  2 18 28  3]
 [11  9 29  7 21 18]
 [14  1 26 23  8 15]
 [21 27  4 11 16 21]
 [16  8 22 16  6 20]]
Number of elements in a= 30
Number of dimensions in a= 2
Rows and Columns in a (5, 6)



In [15]:
#9.
a_matrix=np.full((10,10),9)
np.fill_diagonal(a_matrix,1)
display_shape(a_matrix)



[[1 9 9 9 9 9 9 9 9 9]
 [9 1 9 9 9 9 9 9 9 9]
 [9 9 1 9 9 9 9 9 9 9]
 [9 9 9 1 9 9 9 9 9 9]
 [9 9 9 9 1 9 9 9 9 9]
 [9 9 9 9 9 1 9 9 9 9]
 [9 9 9 9 9 9 1 9 9 9]
 [9 9 9 9 9 9 9 1 9 9]
 [9 9 9 9 9 9 9 9 1 9]
 [9 9 9 9 9 9 9 9 9 1]]
Number of elements in a= 100
Number of dimensions in a= 2
Rows and Columns in a (10, 10)



In [18]:
#10.
import numpy as np
a_matrix=np.random.randint(0,10,(5,10))
print(a_matrix)
print(a_matrix.size)
print(a_matrix.ndim)
print(a_matrix.shape)
print(a_matrix.dtype)



[[4 4 7 8 6 1 0 7 7 4]
 [1 5 5 4 0 9 4 6 6 6]
 [2 3 3 8 9 9 7 8 6 0]
 [1 0 9 5 3 7 3 9 3 2]
 [8 4 2 2 3 1 0 2 3 8]]
50
2
(5, 10)
int32


In [33]:
#11.
import numpy as np
np.random.seed(0)
x3=np.random.randint(10,size=(3,4,7))
x3

array([[[5, 0, 3, 3, 7, 9, 3],
        [5, 2, 4, 7, 6, 8, 8],
        [1, 6, 7, 7, 8, 1, 5],
        [9, 8, 9, 4, 3, 0, 3]],

       [[5, 0, 2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1, 9, 9],
        [0, 4, 7, 3, 2, 7, 2],
        [0, 0, 4, 5, 5, 6, 8]],

       [[4, 1, 4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6, 7, 2],
        [0, 3, 5, 9, 4, 4, 6],
        [4, 4, 3, 4, 4, 8, 4]]])

In [4]:
#12.
import numpy as np
a_array=np.arange(12)
print(a_array)
a_matrix=a_array.reshape(3,4)
print(a_matrix)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
#13.
import numpy as np
from display_shape import display_shape
x1=np.arange(4)
x2=np.arange(4)
x3=np.arange(4)
x4=np.arange(4)
a=np.concatenate([x1,x2,x3,x4])
display_shape(a)



[0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3]
Number of elements in a= 16
Number of dimensions in a= 1
Rows and Columns in a (16,)



In [15]:
#14.
x1=np.arange(3).reshape(3,1)
display_shape(x1)
x2=np.arange(9).reshape(3,3)
display_shape(x2)
#a=np.hstack([x1,x2])
a=np.concatenate([x1,x2],axis=1)
display_shape(a)


[[0]
 [1]
 [2]]
Number of elements in a= 3
Number of dimensions in a= 2
Rows and Columns in a (3, 1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
Number of elements in a= 9
Number of dimensions in a= 2
Rows and Columns in a (3, 3)


[[0 0 1 2]
 [1 3 4 5]
 [2 6 7 8]]
Number of elements in a= 12
Number of dimensions in a= 2
Rows and Columns in a (3, 4)



In [ ]:
#15.
"""Axis bir arrayin boyutu anlamındadır. İki boyutlu bir vektörde, axis 0 satırları, axis 1 sütunları gösterir. """

In [1]:
#16.
import numpy as np
from display_shape import display_shape

np.random.seed(0)
a1=np.random.randint(0,10,(3,4))
a11=np.random.randint(0,20,(3,2))
a2=np.random.randint(0,20,(4,3))
a22=np.random.randint(0,10,(2,3))

a3=np.concatenate((a1,a11),axis=1)
display_shape(a3)
a4=np.concatenate((a2,a22),axis=0)
display_shape(a4)



[[ 5  0  3  3 12  1]
 [ 7  9  3  5  6  7]
 [ 2  4  7  6 14 17]]
Number of elements in a= 18
Number of dimensions in a= 2
Rows and Columns in a (3, 6)


[[ 5 13  8]
 [ 9 19 16]
 [19  5 15]
 [15  0 18]
 [ 3  8  1]
 [ 3  3  3]]
Number of elements in a= 18
Number of dimensions in a= 2
Rows and Columns in a (6, 3)



In [5]:
#17.
a_array=np.arange(10)
display_shape(a_array)
a1,a2,a3,a4,a5=np.split(a_array,[2,4,6,8])
print(a1,a2,a3,a4,a5)


[0 1 2 3 4 5 6 7 8 9]
Number of elements in a= 10
Number of dimensions in a= 1
Rows and Columns in a (10,)

[0 1] [2 3] [4 5] [6 7] [8 9]


In [40]:
#18.
np.random.seed(0)
a1=np.random.randint(0,10,(4,3))
display_shape(a1)
a1.sort(axis=0)
print(a1,end="\n\n")
print(a1.argsort())


[[5 0 3]
 [3 7 9]
 [3 5 2]
 [4 7 6]]
Number of elements in a= 12
Number of dimensions in a= 2
Rows and Columns in a (4, 3)

[[3 0 2]
 [3 5 3]
 [4 7 6]
 [5 7 9]]

[[1 2 0]
 [0 2 1]
 [0 2 1]
 [0 1 2]]


In [47]:
#19.
np.random.seed(0)
a1=np.random.randint(0,10,size=20)
print(a1)
print(a1[2],a1[4],a1[6])

[5 0 3 3 7 9 3 5 2 4 7 6 8 8 1 6 7 7 8 1]
3 7 3


In [49]:
#20.
np.random.seed(0)
a1=np.random.randint(0,10,size=10)
print(a1)
a1[5]=999
print(a1)

[5 0 3 3 7 9 3 5 2 4]
[  5   0   3   3   7 999   3   5   2   4]


In [ ]:
#21.
"""Bir Diagonal Matrix kare matris olup diagonal yani köşegeni harici tüm elemanları dısır olan matristir. 
Bir kare matrisinin köşegenlerinin toplamına Trace of Matrix denir."""

In [53]:
#22.
a_matrix=np.full((5,5),0)
np.fill_diagonal(a_matrix,1)
display_shape(a_matrix)
print(a_matrix[0,0],a_matrix[1,1],a_matrix[2,2])
print(a_matrix[3,3],a_matrix[4,4])


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
Number of elements in a= 25
Number of dimensions in a= 2
Rows and Columns in a (5, 5)

1 1 1
1 1


In [56]:
#23.
np.random.seed(0)
a1=np.random.randint(10,20,size=10)
print(a1)
print(a1[3:])

[15 10 13 13 17 19 13 15 12 14]
[13 17 19 13 15 12 14]


In [75]:
#24.
np.random.seed(0)
a1=np.random.randint(10,200,size=(10,10))
print(a1,end="\n\n")
print(a1[1,:])
print(a1[:,4])
print(a1[2,4])
print(a1[1:7,:])
print(a1[2:5,3:7],end="\n\n")
print(a1[5:,:4])
print(a1[:,3::3],end="\n\n")
a1[5,5]=1979
print(a1,end="\n\n")

[[182  57 127  77 113  19  31  46  97  80]
 [ 98 150  68  49  97 184  98  91 175  35]
 [ 87  82  19 158 125  89 185  92 109 187]
 [ 39 157 157 152 177  42  19 195 137  42]
 [ 41 161 173 124 193  38  44 138 138 174]
 [ 63 143  48  27  89 142 115  52 196  41]
 [130  11  75 179  67  45 112 129  21 184]
 [ 92 101 138 152 109  63 150 131 180  94]
 [ 78  16  57 137 141 110 190  88 153 158]
 [196  33 151 127  95  58  59  79 179 173]]

[ 98 150  68  49  97 184  98  91 175  35]
[113  97 125 177 193  89  67 109 141  95]
125
[[ 98 150  68  49  97 184  98  91 175  35]
 [ 87  82  19 158 125  89 185  92 109 187]
 [ 39 157 157 152 177  42  19 195 137  42]
 [ 41 161 173 124 193  38  44 138 138 174]
 [ 63 143  48  27  89 142 115  52 196  41]
 [130  11  75 179  67  45 112 129  21 184]]
[[158 125  89 185]
 [152 177  42  19]
 [124 193  38  44]]

[[ 63 143  48  27]
 [130  11  75 179]
 [ 92 101 138 152]
 [ 78  16  57 137]
 [196  33 151 127]]
[[ 77  31  80]
 [ 49  98  35]
 [158 185 187]
 [152  19  42]
 [124 

In [86]:
#25.
a1=np.arange(0,50,5)
print(a1)
print(np.count_nonzero(a1>20))
print(np.count_nonzero(a1<30))
print(np.count_nonzero(a1==33))
print(a1*5)
print(a1%2)



[ 0  5 10 15 20 25 30 35 40 45]
5
6
0
[  0  25  50  75 100 125 150 175 200 225]
[0 1 0 1 0 1 0 1 0 1]


In [97]:
#26.
np.random.seed(0)
a1=np.random.random(50)
print(a1,end="\n\n")
print(a1.mean(),end="\n\n")
print(np.std(a1),end="\n\n")
print(np.var(a1),end="\n\n")
print(np.median(a1),end="\n\n")
print(a1.min(),end="\n\n")
print(a1.max(),end="\n\n")


[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492
 0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985
 0.77815675 0.87001215 0.97861834 0.79915856 0.46147936 0.78052918
 0.11827443 0.63992102 0.14335329 0.94466892 0.52184832 0.41466194
 0.26455561 0.77423369 0.45615033 0.56843395 0.0187898  0.6176355
 0.61209572 0.616934   0.94374808 0.6818203  0.3595079  0.43703195
 0.6976312  0.06022547 0.66676672 0.67063787 0.21038256 0.1289263
 0.31542835 0.36371077]

0.5379651182755409

0.27226582292177587

0.0741286783312718

0.5682392549812905

0.018789800436355142

0.978618342232764



In [103]:
#masterodev.
import numpy as np
import time
start_time = time.time()
count = 0
# flag = 1
num = 20
while True:
    count += 1
    mat_1 = np.random.rand(num,num)
    # print('mat1', mat_1 )
    mat_2 = np.random.rand(num,num)
    # print('mat2', mat_2 )
    diago = np.diag(mat_1 - mat_2)
    # print('diago', diago)
    if (np.all((diago > -0.1) & (diago < 0.1)))==True:
        t2=time.time()
        print('I got it!')
        print('diago', diago)
        break
    #if 10 < diago.any() and diago.any() < 10:
        #print('I got it!')
        ##print('diago', diago)
        #break
    #else:
        #continue
finish_time = time.time()
print('Elapsed Time : ', finish_time - start_time )
print()
print('Loop Number  : ', count)
print()
print('Matris       : ', mat_1 - mat_2)
print()